version: '3.4'

services:
  apidesafiointrabank:
    image: ${DOCKER_REGISTRY-}apidesafiointrabank
    container_name: apiclientes
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development


  database:
    container_name: sqlserverdb
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports: 
      - 1450:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Ricardo123@intrabank